### ISSUE TITLE
bibliothèque invalide

### ISSUE THREAD

**Issue by stephcache** [Seeed-Studio/PN532#144]
Bonjour, j'ai télécharger votre bibliothèque pour ajouter au logiciel Arduino et il indique qu'elle n'est pas valide

**Comment by Pr77Pr77** [comment]
Use this repository instead: https://github.com/Seeed-Studio/Seeed_Arduino_NFC
But use the examples from this repository, because in Seeed_Arduino_NFC they aren't working. But you have to add
`#include <NfcAdapter.h>`
and put included files in these signs <> and add `PN532/PN532`
E. g.: 
Replace...
```
#include <SPI.h>
#include <PN532_SPI.h>
#include "PN532.h"
```
with...
```
#include <NfcAdapter.h>

#include <SPI.h>
#include <PN532/PN532_SPI/PN532_SPI.h>
#include <PN532/PN532/PN532.h>
```

**Comment by Cincinnatu** [comment]
> Bonjour， j'ai télécharger votre bibliothèque pour ajouter au logiciel Arduino et il indique qu'elle n'est pas valide

This seems to be able to solve the problem: https://github.com/Seeed-Studio/PN532/issues/144#issuecomment-2198488665.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
